interface Currency {
  name: string;
  symbol: string;
  decimals: number;
}

export const currencies: Record<string, Currency> = {
  AED: { decimals: 2, name: "United Arab Emirates Dirham", symbol: "د.إ" },
  AFN: { decimals: 2, name: "Afghan Afghani", symbol: "؋" },
  ALL: { decimals: 2, name: "Albanian Lek", symbol: "L" },
  AMD: { decimals: 2, name: "Armenian Dram", symbol: "֏" },
  ANG: { decimals: 2, name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  AOA: { decimals: 2, name: "Angolan Kwanza", symbol: "Kz" },
  ARS: { decimals: 2, name: "Argentine Peso", symbol: "$" },
  AUD: { decimals: 2, name: "Australian Dollar", symbol: "A$" },
  AWG: { decimals: 2, name: "Aruban Florin", symbol: "ƒ" },
  AZN: { decimals: 2, name: "Azerbaijani Manat", symbol: "₼" },
  BAM: {
    decimals: 2,
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
  },
  BBD: { decimals: 2, name: "Barbadian Dollar", symbol: "Bds$" },
  BDT: { decimals: 2, name: "Bangladeshi Taka", symbol: "৳" },
  BGN: { decimals: 2, name: "Bulgarian Lev", symbol: "лв" },
  BHD: { decimals: 3, name: "Bahraini Dinar", symbol: ".د.ب" },
  BIF: { decimals: 0, name: "Burundian Franc", symbol: "FBu" },
  BMD: { decimals: 2, name: "Bermudian Dollar", symbol: "Bd$" },
  BND: { decimals: 2, name: "Brunei Dollar", symbol: "B$" },
  BOB: { decimals: 2, name: "Bolivian Boliviano", symbol: "Bs." },
  BOV: { decimals: 2, name: "Bolivian Mvdol", symbol: "BOV" },
  BRL: { decimals: 2, name: "Brazilian Real", symbol: "R$" },
  BSD: { decimals: 2, name: "Bahamian Dollar", symbol: "B$" },
  BTN: { decimals: 2, name: "Bhutanese Ngultrum", symbol: "Nu." },
  BWP: { decimals: 2, name: "Botswanan Pula", symbol: "P" },
  BYN: { decimals: 2, name: "Belarusian Ruble", symbol: "Br" },
  BZD: { decimals: 2, name: "Belize Dollar", symbol: "BZ$" },
  CAD: { decimals: 2, name: "Canadian Dollar", symbol: "C$" },
  CDF: { decimals: 2, name: "Congolese Franc", symbol: "FC" },
  CHE: { decimals: 2, name: "WIR Euro", symbol: "CHE" },
  CHF: { decimals: 2, name: "Swiss Franc", symbol: "CHF" },
  CHW: { decimals: 2, name: "WIR Franc", symbol: "CHW" },
  CLF: { decimals: 4, name: "Chilean Unit of Account (UF)", symbol: "CLF" },
  CLP: { decimals: 0, name: "Chilean Peso", symbol: "CLP$" },
  COP: { decimals: 2, name: "Colombian Peso", symbol: "COL$" },
  COU: { decimals: 2, name: "Colombian Real Value Unit", symbol: "COU" },
  CRC: { decimals: 2, name: "Costa Rican Colón", symbol: "₡" },
  CUC: { decimals: 2, name: "Cuban Convertible Peso", symbol: "CUC$" },
  CUP: { decimals: 2, name: "Cuban Peso", symbol: "CU$" },
  CVE: { decimals: 2, name: "Cape Verdean Escudo", symbol: "Esc" },
  CZK: { decimals: 2, name: "Czech Republic Koruna", symbol: "Kč" },
  DJF: { decimals: 0, name: "Djiboutian Franc", symbol: "Fdj" },
  DKK: { decimals: 2, name: "Danish Krone", symbol: "kr" },
  DOP: { decimals: 2, name: "Dominican Peso", symbol: "RD$" },
  DZD: { decimals: 2, name: "Algerian Dinar", symbol: "د.ج" },
  EGP: { decimals: 2, name: "Egyptian Pound", symbol: "£" },
  ERN: { decimals: 2, name: "Eritrean Nakfa", symbol: "Nfk" },
  ETB: { decimals: 2, name: "Ethiopian Birr", symbol: "Br" },
  EUR: { decimals: 2, name: "Euro", symbol: "€" },
  FJD: { decimals: 2, name: "Fijian Dollar", symbol: "FJ$" },
  FKP: { decimals: 2, name: "Falkland Islands Pound", symbol: "£" },
  GBP: { decimals: 2, name: "Pound Sterling", symbol: "£" },
  GEL: { decimals: 2, name: "Georgian Lari", symbol: "₾" },
  GHS: { decimals: 2, name: "Ghanaian Cedi", symbol: "GH₵" },
  GIP: { decimals: 2, name: "Gibraltar Pound", symbol: "£" },
  GMD: { decimals: 2, name: "Gambian Dalasi", symbol: "D" },
  GNF: { decimals: 0, name: "Guinean Franc", symbol: "FG" },
  GTQ: { decimals: 2, name: "Guatemalan Quetzal", symbol: "Q" },
  GYD: { decimals: 2, name: "Guyanaese Dollar", symbol: "G$" },
  HKD: { decimals: 2, name: "Hong Kong Dollar", symbol: "HK$" },
  HNL: { decimals: 2, name: "Honduran Lempira", symbol: "L" },
  HTG: { decimals: 2, name: "Haitian Gourde", symbol: "G" },
  HUF: { decimals: 2, name: "Hungarian Forint", symbol: "Ft" },
  IDR: { decimals: 2, name: "Indonesian Rupiah", symbol: "Rp" },
  ILS: { decimals: 2, name: "Israeli New Shekel", symbol: "₪" },
  INR: { decimals: 2, name: "Indian Rupee", symbol: "₹" },
  IQD: { decimals: 3, name: "Iraqi Dinar", symbol: "ع.د" },
  IRR: { decimals: 2, name: "Iranian Rial", symbol: "﷼" },
  ISK: { decimals: 0, name: "Icelandic Króna", symbol: "kr" },
  JMD: { decimals: 2, name: "Jamaican Dollar", symbol: "J$" },
  JOD: { decimals: 3, name: "Jordanian Dinar", symbol: "د.ا" },
  JPY: { decimals: 0, name: "Japanese Yen", symbol: "¥" },
  KES: { decimals: 2, name: "Kenyan Shilling", symbol: "KSh" },
  KGS: { decimals: 2, name: "Kyrgystani Som", symbol: "с" },
  KHR: { decimals: 2, name: "Cambodian Riel", symbol: "៛" },
  KMF: { decimals: 0, name: "Comorian Franc", symbol: "CF" },
  KPW: { decimals: 2, name: "North Korean Won", symbol: "₩" },
  KRW: { decimals: 0, name: "South Korean Won", symbol: "₩" },
  KWD: { decimals: 3, name: "Kuwaiti Dinar", symbol: "د.ك" },
  KYD: { decimals: 2, name: "Cayman Islands Dollar", symbol: "CI$" },
  KZT: { decimals: 2, name: "Kazakhstani Tenge", symbol: "₸" },
  LAK: { decimals: 2, name: "Laotian Kip", symbol: "₭" },
  LBP: { decimals: 2, name: "Lebanese Pound", symbol: "ل.ل" },
  LKR: { decimals: 2, name: "Sri Lankan Rupee", symbol: "Rs" },
  LRD: { decimals: 2, name: "Liberian Dollar", symbol: "L$" },
  LSL: { decimals: 2, name: "Lesotho Loti", symbol: "L" },
  LYD: { decimals: 3, name: "Libyan Dinar", symbol: "ل.د" },
  MAD: { decimals: 2, name: "Moroccan Dirham", symbol: "د.م." },
  MDL: { decimals: 2, name: "Moldovan Leu", symbol: "L" },
  MGA: { decimals: 2, name: "Malagasy Ariary", symbol: "Ar" },
  MKD: { decimals: 2, name: "Macedonian Denar", symbol: "ден" },
  MMK: { decimals: 2, name: "Myanmar Kyat", symbol: "K" },
  MNT: { decimals: 2, name: "Mongolian Tugrik", symbol: "₮" },
  MOP: { decimals: 2, name: "Macanese Pataca", symbol: "MOP$" },
  MRU: { decimals: 2, name: "Mauritanian Ouguiya", symbol: "UM" },
  MUR: { decimals: 2, name: "Mauritian Rupee", symbol: "₨" },
  MVR: { decimals: 2, name: "Maldivian Rufiyaa", symbol: "Rf" },
  MWK: { decimals: 2, name: "Malawian Kwacha", symbol: "MK" },
  MXN: { decimals: 2, name: "Mexican Peso", symbol: "Mex$" },
  MXV: {
    decimals: 2,
    name: "Mexican Unidad de Inversion (UDI)",
    symbol: "MXV",
  },
  MYR: { decimals: 2, name: "Malaysian Ringgit", symbol: "RM" },
  MZN: { decimals: 2, name: "Mozambican Metical", symbol: "MT" },
  NAD: { decimals: 2, name: "Namibian Dollar", symbol: "N$" },
  NGN: { decimals: 2, name: "Nigerian Naira", symbol: "₦" },
  NIO: { decimals: 2, name: "Nicaraguan Córdoba", symbol: "C$" },
  NOK: { decimals: 2, name: "Norwegian Krone", symbol: "kr" },
  NPR: { decimals: 2, name: "Nepalese Rupee", symbol: "रू" },
  NZD: { decimals: 2, name: "New Zealand Dollar", symbol: "NZ$" },
  OMR: { decimals: 3, name: "Omani Rial", symbol: "ر.ع." },
  PAB: { decimals: 2, name: "Panamanian Balboa", symbol: "B/." },
  PEN: { decimals: 2, name: "Peruvian Nuevo Sol", symbol: "S/." },
  PGK: { decimals: 2, name: "Papua New Guinean Kina", symbol: "K" },
  PHP: { decimals: 2, name: "Philippine Peso", symbol: "₱" },
  PKR: { decimals: 2, name: "Pakistani Rupee", symbol: "₨" },
  PLN: { decimals: 2, name: "Polish Zloty", symbol: "zł" },
  PYG: { decimals: 0, name: "Paraguayan Guarani", symbol: "₲" },
  QAR: { decimals: 2, name: "Qatari Rial", symbol: "ر.ق" },
  RON: { decimals: 2, name: "Romanian Leu", symbol: "lei" },
  RSD: { decimals: 2, name: "Serbian Dinar", symbol: "дин" },
  CNY: { decimals: 2, name: "Chinese Yuan", symbol: "¥" },
  RUB: { decimals: 2, name: "Russian Ruble", symbol: "₽" },
  RWF: { decimals: 0, name: "Rwandan Franc", symbol: "RF" },
  SAR: { decimals: 2, name: "Saudi Riyal", symbol: "ر.س" },
  SBD: { decimals: 2, name: "Solomon Islands Dollar", symbol: "SI$" },
  SCR: { decimals: 2, name: "Seychellois Rupee", symbol: "₨" },
  SDG: { decimals: 2, name: "Sudanese Pound", symbol: "ج.س" },
  SEK: { decimals: 2, name: "Swedish Krona", symbol: "kr" },
  SGD: { decimals: 2, name: "Singapore Dollar", symbol: "S$" },
  SHP: { decimals: 2, name: "Saint Helena Pound", symbol: "£" },
  SLE: { decimals: 2, name: "Sierra Leonean Leone", symbol: "Le" },
  SLL: { decimals: 2, name: "Sierra Leonean Leone", symbol: "Le" },
  SOS: { decimals: 2, name: "Somali Shilling", symbol: "Sh.So." },
  SRD: { decimals: 2, name: "Surinamese Dollar", symbol: "$" },
  SSP: { decimals: 2, name: "South Sudanese Pound", symbol: "£" },
  STN: { decimals: 2, name: "São Tomé and Príncipe Dobra", symbol: "Db" },
  SVC: { decimals: 2, name: "Salvadoran Colón", symbol: "₡" },
  SYP: { decimals: 2, name: "Syrian Pound", symbol: "£S" },
  SZL: { decimals: 2, name: "Swazi Lilangeni", symbol: "L" },
  THB: { decimals: 2, name: "Thai Baht", symbol: "฿" },
  TJS: { decimals: 2, name: "Tajikistani Somoni", symbol: "SM" },
  TMT: { decimals: 2, name: "Turkmenistani Manat", symbol: "T" },
  TND: { decimals: 3, name: "Tunisian Dinar", symbol: "د.ت" },
  TOP: { decimals: 2, name: "Tongan Pa'anga", symbol: "T$" },
  TRY: { decimals: 2, name: "Turkish Lira", symbol: "₺" },
  TTD: { decimals: 2, name: "Trinidad and Tobago Dollar", symbol: "TT$" },
  TWD: { decimals: 2, name: "New Taiwan Dollar", symbol: "NT$" },
  TZS: { decimals: 2, name: "Tanzanian Shilling", symbol: "Sh" },
  UAH: { decimals: 2, name: "Ukrainian Hryvnia", symbol: "₴" },
  UGX: { decimals: 0, name: "Ugandan Shilling", symbol: "USh" },
  USD: { decimals: 2, name: "United States Dollar", symbol: "$" },
  USN: { decimals: 2, name: "US Dollar (Next day)", symbol: "$" },
  UYI: {
    decimals: 0,
    name: "Uruguay Peso en Unidades Indexadas",
    symbol: "UI",
  },
  UYU: { decimals: 2, name: "Uruguayan Peso", symbol: "$U" },
  UYW: { decimals: 4, name: "Unidad Previsional", symbol: "UP" },
  UZS: { decimals: 2, name: "Uzbekistan Som", symbol: "so'm" },
  VED: { decimals: 2, name: "Venezuelan Bolívar Digital", symbol: "Bs.D" },
  VES: { decimals: 2, name: "Venezuelan Bolívar Soberano", symbol: "Bs.S" },
  VND: { decimals: 0, name: "Vietnamese Dong", symbol: "₫" },
  VUV: { decimals: 0, name: "Vanuatu Vatu", symbol: "VT" },
  WST: { decimals: 2, name: "Samoan Tala", symbol: "WS$" },
  XAF: { decimals: 0, name: "CFA Franc BEAC", symbol: "FCFA" },
  XCD: { decimals: 2, name: "East Caribbean Dollar", symbol: "$" },
  XOF: { decimals: 0, name: "CFA Franc BCEAO", symbol: "CFA" },
  XPF: { decimals: 0, name: "CFP Franc", symbol: "₣" },
  YER: { decimals: 2, name: "Yemeni Rial", symbol: "﷼" },
  ZAR: { decimals: 2, name: "South African Rand", symbol: "R" },
  ZMW: { decimals: 2, name: "Zambian Kwacha", symbol: "ZK" },
  ZWL: { decimals: 2, name: "Zimbabwean Dollar", symbol: "Z$" },
};
